name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Setup dependencies
      run: |
        sudo apt-get install -y llvm-10 clang-10
        sudo update-alternatives \
          --install /usr/bin/llvm-ar llvm-ar /usr/bin/llvm-ar-10 100 \
          --slave /usr/bin/llvm-ranlib llvm-ranlib /usr/bin/llvm-ranlib-10 \
          --slave /usr/bin/llvm-cov llvm-cov /usr/bin/llvm-cov-10
        sudo update-alternatives \
          --install /usr/bin/clang clang /usr/bin/clang-10 100
    - name: Build project
      uses: nicledomaS/cmake_build_action@v1.3
      with:
        config: ${{ matrix.configs }}
        submodule_update: ON
        run_tests: ON
        unit_test_build: -DFIND_TESTS=ON
        cmake_args: -DFIND_MODULES=ON;-DENABLE_TIDY=ON;-DCMAKE_CXX_COMPILER=clang++
    - name: Make-App
      run: cd build && make
    - name: Run-App
      run: ./build/hello